---
# Setup Jenkins on config-srv: configure options + pipeline-style plugins

- name: Change Jenkins Java options
  lineinfile:
    dest: /etc/default/jenkins
    regexp: ^JAVA_ARGS=
    line: JAVA_ARGS="{{jenkins.JAVA_OPTIONS}}"
    create: yes
  become: true

- name: Set Jenkins port to 9000
  lineinfile:
    dest: /etc/default/jenkins
    regexp: ^HTTP_PORT=
    line: "HTTP_PORT={{jenkins.port}}"
  become: true

- name: Start Jenkins service and enable on boot
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Open Port 9000 for Jenkins
  firewalld:
    zone: public
    port: 9000/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true

- name: Add init.groovy.d directory
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
  become: true

- name: Copy basic-security.groovy file to Jenkins
  template:
    src: /bakerx/basic-security.groovy
    dest: /var/lib/jenkins/init.groovy.d
  become: true

- name: Add Jenkins to sudoers file
  lineinfile:
    dest: /etc/sudoers.d/jenkins
    state: present
    create: yes
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  become: true

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
  become: true

- name: "wait for Jenkins to come up"
  uri:
    url: "http://192.168.33.20:9000/login"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 12
  delay: 5

- name: Delete basic-security.groovy script
  file:
    path: /var/lib/jenkins/init.groovy.d/basic-security.groovy
    state: absent
  become: true

- name: Install pipeline plugin
  jenkins_plugin:
    name: build-pipeline-plugin
    url: "http://192.168.33.20:9000"
    url_username: "{{jenkins.username}}"
    url_password: "{{jenkins.password}}"
    timeout: 60
  become: true

- name: Install dsl plugin
  jenkins_plugin:
    name: job-dsl-plugin
    url: "http://192.168.33.20:9000"
    url_username: "{{jenkins.username}}"
    url_password: "{{jenkins.password}}"
    timeout: 60
  become: true

- name: Install workflow aggregator plugin
  jenkins_plugin:
    name: workflow-aggregator
    with_dependencies: yes
    url: "http://192.168.33.20:9000"
    url_username: "{{jenkins.username}}"
    url_password: "{{jenkins.password}}"
    timeout: 60
  become: true

- name: Create environment variables
  lineinfile:
    dest: /etc/environment
    regexp: "^{{item.key}}="
    line: "{{item.key}}={{item.value}}"
    create: yes
  with_items:
    - { key: "DB_ENGINE", value: "{{mongo.DB_ENGINE}}" }
    - { key: "APP_PORT", value: "{{mongo.APP_PORT}}" }
    - { key: "MONGO_PORT", value: "{{mongo.MONGO_PORT}}" }
    - { key: "MONGO_USER", value: "{{mongo.MONGO_USER}}" }
    - { key: "MONGO_PASSWORD", value: "{{mongo.MONGO_PASSWORD}}" }
    - { key: "MONGO_IP", value: "{{mongo.MONGO_IP}}" }
  become: true

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
  become: true

- name: "wait for Jenkins to come up"
  uri:
    url: "http://192.168.33.20:9000/login"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 12
  delay: 5
