
- name: Install nodejs
  apt:
    pkg: nodejs
    state: present
  become: true

- name: Install npm
  apt:
    pkg: npm
    state: present
  become: true

- name: Install mongodb
  apt:
    pkg: mongodb
    state: latest
  become: true

- name: Install nginx
  apt:
    pkg: nginx
    state: present
  become: true

- name: Install pm2 to run checkbox server
  npm:
    name: pm2
    global: yes
    state: present
  become: true

# Unsure if everything below is totally necessary

- name: Install pip3 for Mongo Collection Dependencies     
  apt:
    pkg: python3-pip
    state: latest
  become: true

- name: Installing pymongo
  pip:
    name: pymongo
    state: latest
  become: true

  - name: Start mongodb service
  service:
    name: mongodb
    state: started
    enabled: yes

- name: Open Port 27017 for Mongodb
  firewalld:
    zone: public
    port: 27017/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true

- name: Create mongodb user
  no_log: true
  mongodb_user:
    database: admin
    name: #"{{mongo.MONGO_USER}}"
    password: #"{{mongo.MONGO_PASSWORD}}"
    login_port: #"{{mongo.MONGO_PORT}}"
    roles: readWrite
    state: present
  become: true