---
# Install dependencies for checkbox.io build jobs

- name: Create environment variables
  lineinfile:
    dest: /etc/environment
    regexp: "^{{item.key}}="
    line: "{{item.key}}={{item.value}}"
    create: yes
  with_items:
    - { key: "DB_ENGINE", value: "{{mongo.DB_ENGINE}}" }
    - { key: "APP_PORT", value: "{{mongo.APP_PORT}}" }
    - { key: "MONGO_PORT", value: "{{mongo.MONGO_PORT}}" }
    - { key: "MONGO_USER", value: "{{mongo.MONGO_USER}}" }
    - { key: "MONGO_PASSWORD", value: "{{mongo.MONGO_PASSWORD}}" }
    - { key: "MONGO_IP", value: "{{mongo.MONGO_IP}}" }
  become: true

- name: Ensures /etc/jenkins_jobs dir exists
  file: path=/etc/jenkins_jobs state=directory
  become: true

- name: Copy jenkins_job.ini to correct location
  template:
    src: /bakerx/jenkins_jobs.ini
    dest: /etc/jenkins_jobs/jenkins_jobs.ini
  become: true

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present
  become: true

- name: Install npm
  apt:
    pkg: npm
    state: present
  become: true

- name: Install mongodb
  apt:
    pkg: mongodb
    state: latest
  become: true

- name: Install pip3 for Mongo Collection Dependencies
  apt:
    pkg: python3-pip
    state: latest
  become: true

- name: Install jenkins-job-builder
  pip:
    name: jenkins-job-builder
    state: present

- name: Install pm2 to run checkbox server
  npm:
    name: pm2
    global: yes
    state: present
  become: true

- name: Installing pymongo
  pip:
    name: pymongo
    state: latest
  become: true

- name: Start mongodb service
  service:
    name: mongodb
    state: started
    enabled: yes

- name: Open Port 27017 for Mongodb
  firewalld:
    zone: public
    port: 27017/tcp
    permanent: true
    state: enabled
    immediate: true
  become: true

- name: Create mongodb user
  no_log: true
  mongodb_user:
    database: admin
    name: "{{mongo.MONGO_USER}}"
    password: "{{mongo.MONGO_PASSWORD}}"
    login_port: "{{mongo.MONGO_PORT}}"
    roles: readWrite
    state: present
  become: true
